
package counter;

import counter.progress.ProgressInfo;
import counter.progress.ProgressInfo.Action;
import counter.progress.ProgressObserver;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author grzes
 */
public class MainPanel extends javax.swing.JPanel
{
    MyTableModel tableModel = new MyTableModel();
    WorkoutRunner wr;
    SoundManager sm;
    /**
     * Creates new form MainPanel
     */
    public MainPanel()
    {
        initComponents();
        sm = new SimpleSoundManager();
        try {
            ((SimpleSoundManager) sm).init();
        } catch (LineUnavailableException | UnsupportedAudioFileException | IOException ex) {
            JOptionPane.showMessageDialog(null, "Failed to init sound stuff");
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            sm = new DummySoundManager();
        }
        tableModel.addTableModelListener(new TableModelListener() {
            @Override public void tableChanged(TableModelEvent tme) {
                updateTimeLabel();
            }
        });
        currentWorkoutPanel.setVisible(false);
    }
    
    public void setPlan(WorkoutPlan wp)
    {
        spinnerSeries.setValue(wp.series);
        spinnerBreak.setValue(wp.betweenSeriesTime);
        tableModel.clear();
        for (ExercisePlan ex: wp.exercises)
            tableModel.addExercise(ex);
    }
    
    public WorkoutPlan getPlan()
    {
        WorkoutPlan wp = new WorkoutPlan();
        wp.series = (Integer) spinnerSeries.getValue();
        wp.betweenSeriesTime = (Double) spinnerBreak.getValue();
        for (ExercisePlan ex: tableModel.exercises)
            wp.exercises.add(new ExercisePlan(ex));
        return wp;
    }
    
    void clear()
    {
        spinnerSeries.setValue(1);
        spinnerBreak.setValue(30);
        tableModel.clear();
    }
    
    private void updateTimeLabel()
    {
        double t = getPlan().getTotalTime();
        lblTotalTime.setText(secsToString(t));
    }
    
    private String secsToString(double t)
    {
        int m = (int)(t/60);
        int s = (int)(t - m*60);
        return m + "m " + s + "s";
    }
    
    private void runClicked()
    {
        currentWorkoutPanel.setVisible(true);
        stopButton.setEnabled(true);
        pauseButton.setEnabled(true);
        pauseButton.setText("Pause");
        buttonRun.setEnabled(false);
        wr = new WorkoutRunner(sm);
        wr.addProgressObserver(new ProgressObserver() {
            @Override public void update(ProgressInfo info) {
                showProgress(info);
                if (info.action == Action.FINISHED)
                    clean();
            }
        });
        wr.runInNewThread(getPlan());
    }
                
    private void showProgress(ProgressInfo info)
    {
        seriesLbl.setText("" + info.series);
        exerciseLbl.setText("" + info.exercise);
        repetitionLbl.setText("" + info.repetition);
        remainingLbl.setText(String.format("%.0f sec", info.remainingTime));
        actionLbl.setText(presentAction(info.action));
    }
    
    private void clean()
    {
        pauseButton.setEnabled(false);
        stopButton.setEnabled(false);
        buttonRun.setEnabled(true);
        currentWorkoutPanel.setVisible(false);
    }
    
    
    private String presentAction(ProgressInfo.Action action)
    {
        
        switch(action)
        {
            case REPETITION:
                return "Performing exercise";
            case EXERCISE_BREAK:
                return "Break before exercise";
            case SERIES_BREAK:
                return "Break between series";
            case FINISHED:
                return "Workout finished";
            case STARTING:
                return "Workout initialization";
            default:
                throw new AssertionError(action.name());
            
        }
    }
    
    private void pauseClicked()
    {
        if (wr.isPaused())
        {
            wr.resume();
            pauseButton.setText("Pause");
        }
        else
        {
            wr.pause();
            pauseButton.setText("Resume");
        }
    }
    
    private void stopClicked()
    {
        int res = JOptionPane.showConfirmDialog(this, "Are you sure you want to stop your training?",
                                            "Confirm", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION)
        {
            wr.stop();
            clean();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        spinnerSeries = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        buttonRem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spinnerBreak = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        lblTotalTime = new javax.swing.JLabel();
        buttonRun = new javax.swing.JButton();
        currentWorkoutPanel = new javax.swing.JPanel();
        actionLbl = new javax.swing.JLabel();
        remainingLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        repetitionLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seriesLbl = new javax.swing.JLabel();
        exerciseLbl = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();

        jLabel1.setText("Number of series: ");

        spinnerSeries.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spinnerSeries.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                spinnerSeriesStateChanged(evt);
            }
        });

        table.setModel(tableModel);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(table);

        buttonAdd.setText("Add exercise");
        buttonAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonAddActionPerformed(evt);
            }
        });

        buttonRem.setText("Remove exercise");
        buttonRem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonRemActionPerformed(evt);
            }
        });

        jLabel2.setText("Break between series:");

        spinnerBreak.setModel(new javax.swing.SpinnerNumberModel(30.0d, 0.0d, 1000.0d, 10.0d));
        spinnerBreak.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                spinnerBreakStateChanged(evt);
            }
        });

        jLabel3.setText("Workout time:");

        lblTotalTime.setText("          ");

        buttonRun.setText("Run");
        buttonRun.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonRunActionPerformed(evt);
            }
        });

        currentWorkoutPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Current workout"));

        actionLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        actionLbl.setForeground(new java.awt.Color(0, 0, 255));
        actionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionLbl.setText("jLabel4");

        remainingLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        remainingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remainingLbl.setText("jLabel7");

        repetitionLbl.setText("jLabel7");

        jLabel4.setText("series:");

        jLabel5.setText("exercise: ");

        jLabel6.setText("repetition: ");

        seriesLbl.setText("jLabel7");

        exerciseLbl.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exerciseLbl)
                    .addComponent(repetitionLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(seriesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(exerciseLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(repetitionLbl)))
        );

        javax.swing.GroupLayout currentWorkoutPanelLayout = new javax.swing.GroupLayout(currentWorkoutPanel);
        currentWorkoutPanel.setLayout(currentWorkoutPanelLayout);
        currentWorkoutPanelLayout.setHorizontalGroup(
            currentWorkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentWorkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentWorkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentWorkoutPanelLayout.createSequentialGroup()
                        .addComponent(actionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(currentWorkoutPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remainingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        currentWorkoutPanelLayout.setVerticalGroup(
            currentWorkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentWorkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(currentWorkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentWorkoutPanelLayout.createSequentialGroup()
                        .addComponent(remainingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stopButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pauseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinnerSeries)
                    .addComponent(spinnerBreak))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(stopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(currentWorkoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerBreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(buttonRem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentWorkoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRun)
                    .addComponent(stopButton)
                    .addComponent(pauseButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonRemActionPerformed
    {//GEN-HEADEREND:event_buttonRemActionPerformed
        int row = table.getSelectedRow();
        if (row >= 0)
            tableModel.removeExercise(row);
    }//GEN-LAST:event_buttonRemActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonAddActionPerformed
    {//GEN-HEADEREND:event_buttonAddActionPerformed
        tableModel.addExercise();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void spinnerSeriesStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_spinnerSeriesStateChanged
    {//GEN-HEADEREND:event_spinnerSeriesStateChanged
        updateTimeLabel();
    }//GEN-LAST:event_spinnerSeriesStateChanged

    private void spinnerBreakStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_spinnerBreakStateChanged
    {//GEN-HEADEREND:event_spinnerBreakStateChanged
        updateTimeLabel();
    }//GEN-LAST:event_spinnerBreakStateChanged

    private void buttonRunActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonRunActionPerformed
    {//GEN-HEADEREND:event_buttonRunActionPerformed
        runClicked();
    }//GEN-LAST:event_buttonRunActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stopButtonActionPerformed
    {//GEN-HEADEREND:event_stopButtonActionPerformed
        stopClicked();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pauseButtonActionPerformed
    {//GEN-HEADEREND:event_pauseButtonActionPerformed
        pauseClicked();
    }//GEN-LAST:event_pauseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLbl;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonRem;
    private javax.swing.JButton buttonRun;
    private javax.swing.JPanel currentWorkoutPanel;
    private javax.swing.JLabel exerciseLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalTime;
    private javax.swing.JButton pauseButton;
    private javax.swing.JLabel remainingLbl;
    private javax.swing.JLabel repetitionLbl;
    private javax.swing.JLabel seriesLbl;
    private javax.swing.JSpinner spinnerBreak;
    private javax.swing.JSpinner spinnerSeries;
    private javax.swing.JButton stopButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
